#!/bin/bash
# SessionStart.sh
# Runs at the start of every Claude Code session.
# Output is injected into the context window before the first user message.

echo "========================================="
echo "  GoiFlow — AI Agent Session Start"
echo "========================================="
echo ""
echo "PROJECT: GoiFlow — Japanese learning workflow SaaS"
echo "STACK: Next.js App Router · TypeScript · Prisma · Auth.js · Tailwind CSS v4"
echo "TEST: Vitest (unit+integration) · Playwright (E2E smoke)"
echo ""
echo "KEY RULES (from CLAUDE.md):"
echo "  1. Route ALL data access through src/server/ — never Prisma direct in routes"
echo "  2. MUST run gitnexus_impact before editing any shared symbol"
echo "  3. npm run verify = lint + typecheck + db:validate + test:unit + build"
echo "  4. Auth boundary: every protected route validates session or participantId ownership"
echo "  5. Content queries ALWAYS filter by jlptLevel — no full table scans"
echo ""
echo "CURRENT SPRINT: See PROJECT_ROADMAP_4_SPRINTS.md"
echo "TASK LIST: tasks/todo.md (if it exists)"
echo ""
echo "SKILLS AVAILABLE: /spec /plan /build /test /review /code-simplify /ship"
echo "AGENTS: code-reviewer · test-engineer · security-auditor"
echo ""
echo "SKILL DISCOVERY FLOWCHART:"
echo "  Don't know what to build?     → /spec (interview-me + spec-driven-development)"
echo "  Have spec, need tasks?         → /plan (planning-and-task-breakdown)"
echo "  Implementing code?             → /build (incremental-implementation + TDD)"
echo "  Writing/running tests?         → /test (test-driven-development)"
echo "  Something broke?               → debugging-and-error-recovery skill"
echo "  Reviewing code?                → /review (code-review-and-quality)"
echo "  Deploying/launching?           → /ship (fan-out: reviewer + security + test)"
echo ""
echo "REMINDER: Check DATA_PIPELINE_STRATEGY.md if working on data ingestion."
echo "========================================="
